apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: ${control_plane_endpoint}:6443
    token: ${token}
    unsafeSkipCAVerification: true
nodeRegistration:
  kubeletExtraArgs:
    node-labels: "agentpool=services"
    cloud-provider: "azure"
    cloud-config: "/etc/kubernetes/cloud.conf"
